### Getting all effects
GET http://localhost:3001/api/effects


### Adding new effect
POST http://localhost:3001/api/effects
Content-Type: application/json

{ "effect_id": 3, "effect_name":"Tilt", "effect_description":"Tilting is a technique in which the camera stays in a fixed position but rotates up/down in a vertical plane.", "effect_type":"effect" }


### Delete existing question
DELETE http://localhost:3001/api/effects/delete/3


### Getting all effects
GET http://localhost:3001/api/images/2